### ISSUE TITLE
Post-Editing and Data Augmentation

### ISSUE THREAD

**Issue by ymoslem** [hsing-wang/Awesome-LLM-MT#3]
Many thanks for this wonderful effort! It is very helpful. We are honoured that our paper on utilising in-context learning for adaptive MT with LLMs is on this list.

I would like to mention two of our papers that also employ LLMs for MT. Obviously, it is up to you to decide if their addition fits the purpose of the list.

* [Domain Terminology Integration into Machine Translation: Leveraging Large Language Models](https://arxiv.org/abs/2310.14451)
This paper mostly falls under the post-editing category.

* [Domain-Specific Text Generation for Machine Translation](https://aclanthology.org/2022.amta-research.2.pdf)
This paper uses LLMs for retrieval-based data augmentation to later fine-tune an encoder-decoder MT system. I understand that currently there is no data augmentation subsection. Maybe it can fit under fine-tuning, too.

Thanks again for all your efforts!

**Comment by hsing-wang** [comment]
Thank you for your interest in our repository and for suggesting your work. We have successfully included it in our repository.
